from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('loginlog/', views.loginlog, name='loginlog'),
    path('addrecord/', views.addrecord, name='addrecord'),
    path('indexx/', views.indexx, name='indexx'),
    path('results/', views.results, name='results'),
    #path('index-two/', views.index_two, name='index-two'),
    #path('index-three/', views.index-three, name='index-three'),
    #path('properties/', views.properties, name='properties'),
    path('property-details/<int:id>', views.property_details, name='properties-details'),
    #path('property-alert/', views.properties-alert, name='properties-alert'),
    #path('business-loan/', views.business-loan, name='business-loan'),
    #path('business-loan-details/', views.business-loan-details, name='business-loan-details'),
    #path('list-your-property/', views.list-your-property, name='list-your-property'),
    #path('dashboard/', views.dashboard, name='dashboard'),
    #path('about-us/', views.about-us, name='about-us'),
    #path('affiliate-program/', views.affiliate-program, name='affiliate-program'),
    #path('blog/', views.blog, name='blog'),
    #path('blog-two/', views.blog-two, name='blog-two'),
    #path('blog-single/', views.blog-single, name='blog-single'),
    #path('career/', views.career, name='career'),
    #path('career-details/', views.career-details, name='career-details'),
    #path('how-it-works/', views.how-it-works, name='how-it-works'),
    #path('key-risks/', views.key-risks, name='key-risks'),
    #path('loyalty-program/', views.loyalty-program, name='loyalty-program'),
    #path('terms-conditions/', views.terms-conditions, name='terms-conditions'),
    #path('privacy-policy/', views.privacy-policy, name='privacy-policy'),
    #path('cookie-policy/', views.cookie-policy, name='cookie-policy'),
    #path('support/', views.support, name='support'),
    #path('404/', views.404, name='404'),
    #path('contact-us/', views.contact-us, name='contact-us'),
    #path('loan-application/', views.loan-application, name='loan-application'),
    ##path('logout/', views.logout, name='logout'),
    #path('edit/<int:id>', views.edit, name='edit'),
    #path('editrecord/<int:id>', views.editrecord, name='editrecord'),
    #path('delete/<int:id>', views.delete, name='delete'),
]