# Generated by Django 4.0.6 on 2022-07-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalsapp',
            old_name='password',
            new_name='passs',
        ),
    ]
