# Generated by Django 4.0.6 on 2022-07-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0002_rename_password_rentalsapp_passs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalsapp',
            old_name='passs',
            new_name='password',
        ),
    ]
