# Generated by Django 4.0.6 on 2022-07-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0003_rename_passs_rentalsapp_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='screen_bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenname', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date_added', models.CharField(max_length=255)),
                ('added_by', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
        ),
    ]
