# Generated by Django 4.0.6 on 2022-07-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0004_screen_bookings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screen_bookings',
            old_name='screenname',
            new_name='screen_name',
        ),
        migrations.AlterModelTable(
            name='screen_bookings',
            table='screen_bookings',
        ),
    ]
