# Generated by Django 4.0.6 on 2022-07-29 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0005_rename_screenname_screen_bookings_screen_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='screen_bookings',
            new_name='screenbookings',
        ),
    ]
