# Generated by Django 4.0.6 on 2022-07-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0006_rename_screen_bookings_screenbookings'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='screenbookings',
            table=None,
        ),
    ]
