# Generated by Django 4.0.6 on 2022-07-29 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0007_alter_screenbookings_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenbookings',
            old_name='screen_name',
            new_name='screenname',
        ),
    ]
