# Generated by Django 4.0.6 on 2022-07-29 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0008_rename_screen_name_screenbookings_screenname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screenbookings',
            old_name='screenname',
            new_name='screen_name',
        ),
        migrations.AlterModelTable(
            name='screenbookings',
            table='screen_bookings',
        ),
    ]
