# Generated by Django 4.0.6 on 2022-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0009_rename_screenname_screenbookings_screen_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenbookings',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
