# Generated by Django 4.0.6 on 2022-07-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0010_alter_screenbookings_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenbookings',
            name='screen_name',
        ),
    ]
