# Generated by Django 4.0.6 on 2022-07-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0011_remove_screenbookings_screen_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='screenbook',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('screenname', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date_added', models.CharField(max_length=255)),
                ('added_by', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'screen_book',
            },
        ),
        migrations.DeleteModel(
            name='screenbookings',
        ),
    ]
