# Generated by Django 4.0.6 on 2022-08-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0013_rename_screenbook_screenbooks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenbooks',
            name='picture',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
