# Generated by Django 4.0.6 on 2022-08-02 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0015_remove_screenbooks_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenbooks',
            name='picture',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
