# Generated by Django 4.0.6 on 2022-08-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0016_screenbooks_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screenbooks',
            name='picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
