# Generated by Django 4.0.6 on 2022-08-02 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentalsapp', '0018_remove_screenbooks_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenbooks',
            name='picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
    ]
